version: '3'

services:
  solr:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: w3-braodcast-solr
    ports:
    - "8983:8983"
    volumes:
      - ./headlines:/opt/solr/server/solr/headlines/conf
