version: '3'

services:
  solr:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: w3-braodcast-solr
    ports:
      - "8983:8983"
    volumes:
      - ./headlines:/opt/solr/server/solr/headlines/conf
      - ./example-scenarios/migration-alias/new-schema:/opt/solr/server/solr/new-headlines-schema/conf
